apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argowf
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/argo-workflows
    repoURL: 'https://github.com/sungwook-practice/terraform-study.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
