apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: standalone-minio
  namespace: argowf
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: minio
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/minio
    repoURL: 'https://github.com/sungwook-practice/terraform-study.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - override_values.yaml
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
