apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: argowf-postgres
  namespace: argowf
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:14.2
  instances: 1
  storage:
    size: 1Gi
  postgresql:
    parameters:
      max_worker_processes: "40"
      timezone: "Asia/Seoul"
    pg_hba:
      - host all postgres all trust
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: app
