{{- $global := . -}}
{{- if .Values.svcaccts }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "minio.fullname" . }}-make-svcacct-job
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "minio.name" . }}-make-svcacct-job
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- with .Values.makeServiceAccountJob.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "minio.name" . }}-job
        release: {{ .Release.Name }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
{{- if .Values.makeServiceAccountJob.podAnnotations }}
      annotations:
{{ toYaml .Values.makeServiceAccountJob.podAnnotations | indent 8 }}
{{- end }}
    spec:
      restartPolicy: OnFailure
{{- include "minio.imagePullSecrets" . | indent 6 }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.makeServiceAccountJob.nodeSelector | indent 8 }}
{{- end }}
{{- with .Values.makeServiceAccountJob.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.makeServiceAccountJob.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.makeServiceAccountJob.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.makeServiceAccountJob.securityContext.runAsUser }}
        runAsGroup: {{ .Values.makeServiceAccountJob.securityContext.runAsGroup }}
        fsGroup: {{ .Values.makeServiceAccountJob.securityContext.fsGroup }}
{{- end }}
      volumes:
        - name: minio-configuration
          projected:
            sources:
            - configMap:
                name: {{ template "minio.fullname" . }}
            - secret:
                name: {{ template "minio.secretName" . }}
            {{- range .Values.svcaccts }}
            {{- if .existingSecret }}
            - secret:
                name: {{ tpl .existingSecret $global }}
                items:
                  - key: {{ .existingSecretKey }}
                    path: secrets/{{ tpl .existingSecret $global }}/{{ tpl .existingSecretKey $global }}
            {{- end }}
            {{- end }}
        {{- if .Values.tls.enabled }}
        - name: cert-secret-volume-mc
          secret:
            secretName: {{ .Values.tls.certSecret }}
            items:
            - key: {{ .Values.tls.publicCrt }}
              path: CAs/public.crt
        {{ end }}
        {{- if .Values.makeServiceAccountJob.extraVolumes }}
          {{- toYaml .Values.makeServiceAccountJob.extraVolumes | nindent 8 }}
        {{- end }}
{{ if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
{{- end }}
      containers:
      - name: minio-mc
        image: "{{ .Values.mcImage.repository }}:{{ .Values.mcImage.tag }}"
        imagePullPolicy: {{ .Values.mcImage.pullPolicy }}
        {{- if .Values.makeServiceAccountJob.exitCommand }}
        command: ["/bin/sh", "-c"]
        args: ["/bin/sh /config/add-svcacct; x=$(echo $?); {{ .Values.makeServiceAccountJob.exitCommand }} && exit $x" ]
        {{- else }}
        command: ["/bin/sh", "/config/add-svcacct"]
        {{- end }}
        env:
          - name: MINIO_ENDPOINT
            value: {{ template "minio.fullname" . }}
          - name: MINIO_PORT
            value: {{ .Values.service.port | quote }}
        volumeMounts:
          - name: minio-configuration
            mountPath: /config
          {{- if .Values.tls.enabled }}
          - name: cert-secret-volume-mc
            mountPath: {{ .Values.configPathmc }}certs
          {{ end }}
          {{- if .Values.makeServiceAccountJob.extraVolumeMounts }}
            {{- toYaml .Values.makeServiceAccountJob.extraVolumeMounts | nindent 10 }}
          {{- end }}
        resources:
{{ toYaml .Values.makeServiceAccountJob.resources | indent 10 }}
{{- end }}
