server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - argowf.localtest

controller:
  singleNamespace: true
  persistence:
    archive: true
    postgresql:
      host: argowf-rw.cnpg.svc
      port: 5432
      database: postgres
      tableName: argo_workflows
      userNameSecret:
        name: argwf-postgres-user
        key: username

useDefaultArtifactRepo: true
artifactRepository:
  archiveLogs: true
  s3:
    endpoint: standalone-minio.argowf.svc:9000
    insecure: true
    bucket: argo-workflow
    accessKeySecret:
      name: argwf-user
      key: accesskey
    secretKeySecret:
      name: argwf-user
      key: secretkey
